import{FormEvent,useState}from"react";
import CityScene from './CityScene';
import{requestAiReply}from'./ai';
import{ArrowLeft,ArrowRight,Bus,Check,Coffee,Hotel,Lightbulb,MapPin,MessageCircle,RotateCcw,ShoppingBasket,UtensilsCrossed}from"lucide-react";
import{analyzeConversation,clerkReply,completedCount,Criteria,criterionLabels,currentOrderTarget,emptyCriteria,hints,normalizeVietnamese,orderSummary,randomizeOrderTarget,recommendedExpression}from"./engine";
type Screen="home"|"map"|"mission"|"chat"|"report";type ChatMessage={role:"clerk"|"user";vi:string;zh?:string};type SavedReport={score:number;completedAt:string;expressions:string[];criteria:Criteria;hints:number};
const STORAGE_KEY="hanoi-one-day-reports",steps:Screen[]=["home","map","mission","chat","report"],labels:Record<Screen,string>={home:"首页",map:"城市地图",mission:"任务介绍",chat:"对话场景",report:"任务报告"};
const places=[{name:"街角咖啡店",note:"今日任务 · A1",icon:Coffee,active:true},{name:"同春市场",note:"即将开放 · A2",icon:ShoppingBasket},{name:"老街酒店",note:"即将开放 · A2",icon:Hotel},{name:"公交站",note:"即将开放 · A1",icon:Bus},{name:"河内餐馆",note:"即将开放 · A2",icon:UtensilsCrossed}];
function loadReports():SavedReport[]{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
export default function App(){const[screen,setScreen]=useState<Screen>("home"),[messages,setMessages]=useState<ChatMessage[]>([{role:"clerk",vi:"Xin chào! Bạn muốn uống gì?",zh:"你好！你想喝什么？"}]),[criteria,setCriteria]=useState<Criteria>(emptyCriteria),[hintsUsed,setHintsUsed]=useState(0),[report,setReport]=useState<SavedReport|null>(null),[reports,setReports]=useState<SavedReport[]>(loadReports),step=steps.indexOf(screen);const resetMission=()=>{setMessages([{role:"clerk",vi:"Xin chào! Bạn muốn uống gì?",zh:"你好！你想喝什么？"}]);setCriteria(emptyCriteria);setHintsUsed(0);setReport(null);setScreen("chat")},back=()=>setScreen(steps[Math.max(step-1,0)]),finish=(finalCriteria:Criteria,finalMessages:ChatMessage[])=>{const result:SavedReport={score:Math.max(0,completedCount(finalCriteria)*20-hintsUsed*2),completedAt:new Date().toISOString(),expressions:finalMessages.filter(m=>m.role==="user").map(m=>m.vi),criteria:finalCriteria,hints:hintsUsed},updated=[result,...reports].slice(0,10);localStorage.setItem(STORAGE_KEY,JSON.stringify(updated));setReports(updated);setReport(result);window.setTimeout(()=>setScreen("report"),650)};return <main className="app-shell"><header className="topbar"><button className="brand" onClick={()=>setScreen("home")} aria-label="返回首页"><span className="brand-mark">河</span><span>河内的一天</span></button><div className="step-label">{String(step+1).padStart(2,"0")} / 05 · {labels[screen]}</div></header><section className={`screen screen-${screen}`}>{screen==="home"&&<Home onStart={()=>setScreen("map")} latest={reports[0]}/>} {screen==="map"&&<MapView onEnter={()=>setScreen("mission")}/>} {screen==="mission"&&<Mission onStart={resetMission}/>} {screen==="chat"&&<Chat messages={messages} setMessages={setMessages} criteria={criteria} setCriteria={setCriteria} hintsUsed={hintsUsed} setHintsUsed={setHintsUsed} onComplete={finish}/>} {screen==="report"&&report&&<Report report={report} onRetry={resetMission} onMap={()=>setScreen("map")}/>}</section>{screen!=="home"&&screen!=="report"&&<button className="back-button" onClick={back}><ArrowLeft size={18}/> 返回</button>}</main>}
function Home({onStart,latest}:{onStart:()=>void;latest?:SavedReport}){return <div className="hero"><div className="hero-copy"><p className="eyebrow">VIETNAMESE · CITY PRACTICE</p><h1>河内的<br/><em>一天</em></h1><p className="subtitle">在一座虚拟城市中学习真实的越南语</p><div className="home-actions"><button className="primary-button" onClick={onStart}>{latest?"继续探索":"开始体验"} <ArrowRight size={20}/></button>{latest&&<div className="last-score"><strong>{latest.score}</strong><span>上次任务得分</span></div>}</div></div><div className="street-card" aria-label="河内咖啡店氛围图形"><span className="sun"/><div className="awning"><span/><span/><span/><span/><span/></div><div className="shop-sign">CÀ PHÊ</div><div className="shop-window"><Coffee size={54}/></div><div className="street-line"/><div className="scooter">○━●</div><p>Phố cổ · Hà Nội</p></div></div>}
function MapView({onEnter}:{onEnter:()=>void}){return <CityScene onEnter={()=>{randomizeOrderTarget();onEnter()}}/>}
function Mission({onStart}:{onStart:()=>void}){return <div className="page-wrap narrow"><p className="eyebrow">任务 01 · 街角咖啡店 · A1</p><h2>这次，请点<br/>{orderSummary()}</h2><div className="scenario-note"><strong>你的情境</strong><p>上午九点，你走进河内老城区的一家咖啡店。请用越南语完成这张随机订单。</p></div><div className="mission-card"><p>必须完成 5 个目标：</p><ul>{Object.values(criterionLabels).map((label,index)=><li key={label}><span>{String(index+1).padStart(2,"0")}</span>{label}</li>)}</ul></div><p className="tip">每次从地图进入都会生成新订单。系统可以理解无声调、大小写和常见空格问题。</p><button className="primary-button" onClick={onStart}>进入咖啡店 <ArrowRight size={20}/></button></div>}
function Chat({messages,setMessages,criteria,setCriteria,hintsUsed,setHintsUsed,onComplete}:{messages:ChatMessage[];setMessages:(v:ChatMessage[])=>void;criteria:Criteria;setCriteria:(v:Criteria)=>void;hintsUsed:number;setHintsUsed:(v:number)=>void;onComplete:(c:Criteria,m:ChatMessage[])=>void}){
  const[input,setInput]=useState("");
  const[isReacting,setIsReacting]=useState(false);
  const[isSending,setIsSending]=useState(false);
  const progress=completedCount(criteria);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!input.trim()||isSending)return;const userMessage:ChatMessage={role:"user",vi:input.trim()},pendingMessages=[...messages,userMessage],allUserInputs=pendingMessages.filter(m=>m.role==="user").map(m=>m.vi),nextCriteria=analyzeConversation(allUserInputs,currentOrderTarget),fallbackReply=clerkReply(nextCriteria,allUserInputs,currentOrderTarget);setMessages(pendingMessages);setCriteria(nextCriteria);setInput("");setIsReacting(true);setIsSending(true);const aiReply=await requestAiReply({messages:pendingMessages,target:currentOrderTarget,criteria:nextCriteria,suggestedReply:fallbackReply,task:orderSummary()});const nextMessages=[...pendingMessages,{role:"clerk" as const,...(aiReply||fallbackReply)}];setMessages(nextMessages);setIsSending(false);window.setTimeout(()=>setIsReacting(false),720);if(completedCount(nextCriteria)===5)onComplete(nextCriteria,nextMessages)};
  return <div className="chat-layout dialogue-stage"><section className="conversation"><div className="conversation-head"><div><p className="eyebrow">街角咖啡店 · 规则型对话</p><h2>和 Lạc 对话</h2></div><div className="progress-compact"><span>{progress}/5</span><div className="progress"><i style={{width:`${progress*20}%`}}/></div></div></div><div className="task-chips">{(Object.keys(criteria)as(keyof Criteria)[]).map(key=><span className={criteria[key]?"done":""} key={key}>{criteria[key]&&<Check size={13}/>} {criterionLabels[key]}</span>)}</div><div className="messages" aria-live="polite">{messages.map((m,i)=><div className={`bubble ${m.role}`} key={`${m.role}-${i}`}><small>{m.role==="clerk"?"Lạc · 店员":"你"}</small>{m.vi}{m.zh&&<span>{m.zh}</span>}</div>)}</div>{hintsUsed>0&&<div className="hint-panel"><Lightbulb size={18}/><span>{hints[hintsUsed-1]}</span></div>}<form className="composer" onSubmit={submit}><button type="button" className="hint-button" onClick={()=>setHintsUsed(Math.min(hintsUsed+1,hints.length))} disabled={hintsUsed>=hints.length}>提示 {hintsUsed}/3</button><input value={input} onChange={e=>setInput(e.target.value)} aria-label="越南语输入" placeholder="例如：Cho tôi một ly cà phê sữa đá…" autoComplete="off"/><button className="send-button" type="submit">发送</button></form></section><aside className={`character-stage ${isReacting?"reacting":""}`} aria-label="咖啡店店员 Lạc"><div className="character-glow"/><div className="speech-status"><span/><strong>{isReacting?"Lạc 正在回应…":"Lạc 正在等你点单"}</strong></div><img src={`${import.meta.env.BASE_URL}lac-clerk.png`} alt="二次元咖啡店店员 Lạc"/><div className="character-label"><strong>Lạc</strong><span>店员 · Nhân viên</span></div></aside></div>
}
function Report({report,onRetry,onMap}:{report:SavedReport;onRetry:()=>void;onMap:()=>void}){const nonStandard=report.expressions.filter(text=>normalizeVietnamese(text)===text.toLowerCase().replace(/\s+/g," ").trim());return <div className="report-page"><div className="report-heading"><div><p className="eyebrow">任务报告 · 已保存到本机</p><h2>{report.score>=80?"任务完成，干得漂亮！":"完成了，再练一次会更好。"}</h2><p className="lead">你已经成功完成咖啡店沟通。下面是这次练习的详细反馈。</p></div><div className="score-card"><strong>{report.score}</strong><span>/ 100</span><p>综合得分</p></div></div><div className="report-grid"><section className="report-panel"><h3>分项表现</h3>{(Object.keys(report.criteria)as(keyof Criteria)[]).map(key=><div className="report-row" key={key}><span>{criterionLabels[key]}</span><strong>{report.criteria[key]?"20 / 20":"0 / 20"}</strong></div>)}{report.hints>0&&<p className="deduction">使用 {report.hints} 次提示，独立完成分扣除 {report.hints*2} 分。</p>}</section><section className="report-panel"><h3>你的表达</h3>{report.expressions.map((text,index)=><p className="expression" key={index}>{text}</p>)}<h3>规范与建议</h3><p>{nonStandard.length>0?"系统理解了你的无声调表达。正式书写时，请补全越南语声调符号。":"你的表达包含了规范的越南语声调，继续保持。"}</p><div className="recommended"><small>推荐表达</small>{recommendedExpression}</div></section></div><div className="report-actions"><button className="secondary-button" onClick={onMap}>返回城市地图</button><button className="primary-button" onClick={onRetry}><RotateCcw size={18}/> 再练一次</button></div></div>}
