import{FormEvent,useEffect,useRef,useState}from"react";
import CityScene from './CityScene';
import { asset, loadCity, warmCafe } from './loading';
import{AiFeedback,ClerkMood,isAiConfigured,requestAiFeedback,requestAiReply}from'./ai';
import{ArrowLeft,ArrowRight,Check,Coffee,Lightbulb,RotateCcw,X}from"lucide-react";
import{analyzeAttempts,Assessment,clerkReply,correctCriteria,Criteria,criterionLabels,currentOrderTarget,emptyAssessment,finalScore,hints,mergeAssessment,normalizeVietnamese,orderSummary,randomizeOrderTarget,recommendedExpression,resolvedCount,resolvedCriteria}from"./engine";
type Screen="home"|"map"|"mission"|"chat"|"report";type ChatMessage={role:"clerk"|"user";vi:string;zh?:string};type SavedReport={score:number;objectiveScore:number;completedAt:string;expressions:string[];criteria:Criteria;assessment:Assessment;hints:number;feedback:AiFeedback|null;feedbackUnavailable?:boolean};
const STORAGE_KEY="hanoi-one-day-reports",steps:Screen[]=["home","map","mission","chat","report"],labels:Record<Screen,string>={home:"首页",map:"城市地图",mission:"任务介绍",chat:"对话场景",report:"任务报告"};
const clerkSprite=(mood:ClerkMood,size:448|768)=>asset(`clerk${mood==='neutral'?'':`-${mood}`}-${size}.webp`);
function loadReports():SavedReport[]{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
export default function App(){
  const[screen,setScreen]=useState<Screen>('home'),[messages,setMessages]=useState<ChatMessage[]>([{role:'clerk',vi:'Xin chào! Bạn muốn uống gì?',zh:'你好！你想喝什么？'}]),[assessment,setAssessment]=useState<Assessment>(emptyAssessment),[hintsUsed,setHintsUsed]=useState(0),[report,setReport]=useState<SavedReport|null>(null),[reports,setReports]=useState<SavedReport[]>(loadReports),step=steps.indexOf(screen);
  const resetMission=()=>{setMessages([{role:'clerk',vi:'Xin chào! Bạn muốn uống gì?',zh:'你好！你想喝什么？'}]);setAssessment({...emptyAssessment});setHintsUsed(0);setReport(null);setScreen('chat')};
  useEffect(()=>{const timer=window.setTimeout(()=>{if(screen==='home')void loadCity().catch(()=>{});if(screen==='map'||screen==='mission')warmCafe();},screen==='home'?1200:300);return()=>window.clearTimeout(timer)},[screen]);
  const back=()=>setScreen(steps[Math.max(step-1,0)]);
  const finish=async(finalAssessment:Assessment,finalMessages:ChatMessage[])=>{
    const base=Math.max(0,Object.values(finalAssessment).filter(value=>value==='correct').length*15-hintsUsed*2);
    const result:SavedReport={score:base,objectiveScore:base,completedAt:new Date().toISOString(),expressions:finalMessages.filter(message=>message.role==='user').map(message=>message.vi),criteria:correctCriteria(finalAssessment),assessment:finalAssessment,hints:hintsUsed,feedback:null};
    const save=(value:SavedReport)=>{const updated=[value,...reports].slice(0,10);localStorage.setItem(STORAGE_KEY,JSON.stringify(updated));setReports(updated);setReport(value)};
    save(result);setScreen('report');
    const feedback=await requestAiFeedback({messages:finalMessages,target:currentOrderTarget,assessment:finalAssessment});
    save(feedback?{...result,score:finalScore(finalAssessment,feedback.languageScore,hintsUsed),feedback}:{...result,feedbackUnavailable:true});
  };
  return <main className="app-shell"><header className="topbar"><button className="brand" onClick={()=>setScreen('home')} aria-label="返回首页"><span className="brand-mark">河</span><span>河内的一天</span></button><div className="step-label">{String(step+1).padStart(2,'0')} / 05 · {labels[screen]}</div></header><section key={screen} className={`screen screen-${screen}`}>{screen==='home'&&<Home onStart={()=>setScreen('map')} latest={reports[0]}/>} {screen==='map'&&<MapView onEnter={()=>setScreen('mission')}/>} {screen==='mission'&&<Mission onStart={resetMission}/>} {screen==='chat'&&<Chat messages={messages} setMessages={setMessages} assessment={assessment} setAssessment={setAssessment} hintsUsed={hintsUsed} setHintsUsed={setHintsUsed} onComplete={finish}/>} {screen==='report'&&report&&<Report report={report} onRetry={resetMission} onMap={()=>setScreen('map')}/>}</section>{screen!=='home'&&screen!=='report'&&<button className="back-button" onClick={back}><ArrowLeft size={18}/> 返回</button>}</main>
}
function Home({onStart,latest}:{onStart:()=>void;latest?:SavedReport}){return <div className="hero"><div className="hero-copy"><p className="eyebrow">VIETNAMESE · CITY PRACTICE</p><h1>河内的<br/><em>一天</em></h1><p className="subtitle">在一座虚拟城市中学习真实的越南语</p><div className="home-actions"><button className="primary-button" onClick={onStart}>{latest?"继续探索":"开始体验"} <ArrowRight size={20}/></button>{latest&&<div className="last-score"><strong>{latest.score}</strong><span>上次任务得分</span></div>}</div></div><div className="street-card" aria-label="河内咖啡店氛围图形"><span className="sun"/><div className="awning"><span/><span/><span/><span/><span/></div><div className="shop-sign">CÀ PHÊ</div><div className="shop-window"><Coffee size={54}/></div><div className="street-line"/><div className="scooter">○━●</div><p>Phố cổ · Hà Nội</p></div></div>}
function MapView({onEnter}:{onEnter:()=>void}){return <CityScene onEnter={()=>{randomizeOrderTarget();onEnter()}}/>}
function Mission({onStart}:{onStart:()=>void}){return <div className="page-wrap narrow"><p className="eyebrow">任务 01 · 街角咖啡店 · A1</p><h2>这次，请点<br/>{orderSummary()}</h2><div className="scenario-note"><strong>你的情境</strong><p>上午九点，你走进河内老城区的一家咖啡店。请用越南语完成这张随机订单。</p></div><div className="mission-card"><p>需要作答 5 个目标（每项只有一次评分机会）：</p><ul>{Object.values(criterionLabels).map((label,index)=><li key={label}><span>{String(index+1).padStart(2,"0")}</span>{label}</li>)}</ul></div><p className="tip">答错也能继续对话，但首次明确作答的结果会锁定。系统可以理解无声调、大小写和常见空格问题。</p><button className="primary-button" onClick={onStart}>进入咖啡店 <ArrowRight size={20}/></button></div>}
function Chat({messages,setMessages,assessment,setAssessment,hintsUsed,setHintsUsed,onComplete}:{messages:ChatMessage[];setMessages:(v:ChatMessage[])=>void;assessment:Assessment;setAssessment:(v:Assessment)=>void;hintsUsed:number;setHintsUsed:(v:number)=>void;onComplete:(a:Assessment,m:ChatMessage[])=>void}){
  const[input,setInput]=useState("");
  const[isReacting,setIsReacting]=useState(false);
  const[isSending,setIsSending]=useState(false);
  const[clerkMood,setClerkMood]=useState<ClerkMood>('neutral');
  const messagesRef=useRef<HTMLDivElement>(null);
  const latestMessageRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const list=messagesRef.current;list?.scrollTo?.({top:list.scrollHeight,behavior:'smooth'});latestMessageRef.current?.scrollIntoView?.({behavior:'smooth',block:'nearest'})},[messages,isSending]);
  const progress=resolvedCount(assessment);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!input.trim()||isSending)return;const userMessage:ChatMessage={role:'user',vi:input.trim()},pendingMessages=[...messages,userMessage],allUserInputs=pendingMessages.filter(m=>m.role==='user').map(m=>m.vi),ruleAssessment=mergeAssessment(assessment,analyzeAttempts(userMessage.vi,currentOrderTarget)),resolved=resolvedCriteria(ruleAssessment),fallbackReply=clerkReply(resolved,allUserInputs,currentOrderTarget);setMessages(pendingMessages);setAssessment(ruleAssessment);setInput('');setIsReacting(true);setIsSending(true);setClerkMood('listening');const aiReply=await requestAiReply({messages:pendingMessages,target:currentOrderTarget,criteria:resolved,assessment:ruleAssessment,beforeAssessment:assessment,suggestedReply:fallbackReply,task:orderSummary()}),finalAssessment=mergeAssessment(ruleAssessment,aiReply?.attempts||{}),nextPrompt=clerkReply(resolvedCriteria(finalAssessment),allUserInputs,currentOrderTarget),safeReply=aiReply||nextPrompt,nextMessages=[...pendingMessages,{role:'clerk' as const,...safeReply}],attempts=Object.values(aiReply?.attempts||{}),nextMood:ClerkMood=aiReply?.mood||(attempts.includes('incorrect')||!attempts.includes('correct')?'clarify':'happy');setAssessment(finalAssessment);setMessages(nextMessages);setClerkMood(nextMood);setIsSending(false);window.setTimeout(()=>setIsReacting(false),720);if(resolvedCount(finalAssessment)===5)onComplete(finalAssessment,nextMessages)};
  return <div className="cafe-scene dialogue-stage">
    <div className="cafe-ambient" aria-hidden="true"/>
    <aside className="cafe-task" aria-label="当前任务">
      <div className="cafe-task-title"><span>今日任务 · 01</span><strong>{orderSummary()}</strong><div className="progress-compact"><span>{progress}/5</span><div className="progress"><i style={{width:`${progress*20}%`}}/></div></div></div>
      <div className="task-chips">{(Object.keys(assessment)as(keyof Assessment)[]).map(key=><span className={assessment[key]==='correct'?'done':assessment[key]==='incorrect'?'incorrect':''} key={key} aria-label={`${criterionLabels[key]}：${assessment[key]==='correct'?'正确':assessment[key]==='incorrect'?'错误':'未作答'}`}>{assessment[key]==='correct'&&<Check size={13}/>} {assessment[key]==='incorrect'&&<X size={13}/>} {criterionLabels[key]}</span>)}</div>
    </aside>
    <aside className={`character-stage mood-${clerkMood} ${isReacting?'reacting':''}`} aria-label="咖啡店店员 Lạc"><div className="character-glow"/><div className="speech-status"><span/><strong>{isSending?'Lạc 正在理解你的话…':'Lạc 正在等你点单'}</strong></div><picture key={clerkMood} style={{display:"contents"}}><source media="(max-width: 760px)" srcSet={clerkSprite(clerkMood,448)}/><img src={clerkSprite(clerkMood,768)} decoding="async" fetchPriority="high" alt="二次元咖啡店店员 Lạc"/></picture><div className="character-label"><strong>Lạc</strong><span>店员 · Nhân viên</span></div></aside>
    <section className="conversation"><div className="conversation-head"><div><p className="eyebrow">街角咖啡店 · {isAiConfigured?'AI 对话':'规则型对话'}</p><h2>和 Lạc 对话</h2></div></div><div className="messages" ref={messagesRef} aria-live="polite">{messages.map((m,i)=><div className={`bubble ${m.role}`} key={`${m.role}-${i}`}><small>{m.role==='clerk'?'Lạc · 店员':'你'}</small>{m.vi}{m.zh&&<span>{m.zh}</span>}</div>)}{isSending&&<div className="bubble clerk thinking-bubble" role="status" aria-label="Lạc 正在思考"><small>Lạc · 店员</small><span className="thinking-content">正在思考<span className="thinking-dots" aria-hidden="true"><i/><i/><i/></span></span></div>}<div ref={latestMessageRef} className="message-end" aria-hidden="true"/></div>{hintsUsed>0&&<div className="hint-panel"><Lightbulb size={18}/><span>{hints[hintsUsed-1]}</span></div>}<form className="composer" onSubmit={submit}><button type="button" className="hint-button" onClick={()=>setHintsUsed(Math.min(hintsUsed+1,hints.length))} disabled={hintsUsed>=hints.length}>提示 {hintsUsed}/3</button><input value={input} onChange={e=>setInput(e.target.value)} aria-label="越南语输入" placeholder="例如：Cho tôi một ly cà phê sữa đá…" autoComplete="off"/><button className="send-button" type="submit" disabled={isSending}>{isSending?'回复中…':'发送'}</button></form></section>
  </div>
}
function Report({report,onRetry,onMap}:{report:SavedReport;onRetry:()=>void;onMap:()=>void}){
  const nonStandard=report.expressions.filter(text=>normalizeVietnamese(text)===text.toLowerCase().replace(/\s+/g,' ').trim());
  return <div className="report-page"><div className="report-heading"><div><p className="eyebrow">任务报告 · 已保存到本机</p><h2>{Object.values(report.assessment).every(value=>value==='correct')?'任务完成，干得漂亮！':'任务已结束，看看哪里还能进步。'}</h2><p className="lead">五项任务以首次明确回答评分；答错也能继续。语言分与学习建议由 AI 辅助分析。</p></div><div className="score-card"><strong>{report.score}</strong><span>/ 100</span><p>{report.feedback?'综合得分':'当前任务得分 · 语言分待评'}</p></div></div><div className="report-grid"><section className="report-panel"><h3>任务正确性 · {report.objectiveScore}/75</h3>{(Object.keys(report.assessment)as(keyof Assessment)[]).map(key=><div className="report-row" key={key}><span>{criterionLabels[key]}</span><strong>{report.assessment[key]==='correct'?'✓ 15 / 15':'× 0 / 15'}</strong></div>)}{report.hints>0&&<p className="deduction">使用 {report.hints} 次提示，扣除 {report.hints*2} 分。</p>}{Object.values(report.assessment).includes('incorrect')&&<p className="deduction">有项目首次作答错误，综合分最高为 79；语言分不能抵消任务错误。</p>}<h3>语言表达 · {report.feedback?`${report.feedback.languageScore}/25`:'待评'}</h3><p>{report.feedback?'AI 辅助评分，不改变上方首次答案的对错。':report.feedbackUnavailable?'AI 暂时不可用：只显示已确定的任务分，不会虚构语言分。':'正在获取 AI 学习反馈；任务分已保存。'}</p></section><section className="report-panel"><h3>你的表达</h3>{report.expressions.map((text,index)=><p className="expression" key={index}>{text}</p>)}<h3>规范与建议</h3><p>{nonStandard.length>0?'系统理解了你的无声调表达。正式书写时，请补全越南语声调符号。':'你的表达包含了规范的越南语声调，继续保持。'}</p>{report.feedback&&<><p><strong>语法：</strong>{report.feedback.grammar}</p><p><strong>词汇：</strong>{report.feedback.vocabulary}</p><p><strong>自然度：</strong>{report.feedback.naturalness}</p><h3>下一步练习</h3><ul>{report.feedback.advice.map((item,index)=><li key={index}>{item}</li>)}</ul></>}<div className="recommended"><small>推荐表达</small>{recommendedExpression}</div></section></div><div className="report-actions"><button className="secondary-button" onClick={onMap}>返回城市地图</button><button className="primary-button" onClick={onRetry}><RotateCcw size={18}/> 再练一次</button></div></div>
}
