import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import App from './App';
vi.mock('./cityRenderer', () => ({mountCity: () => { throw new Error('WebGL unavailable'); }}));
beforeEach(()=>{const values=[0,0,.5,0];let index=0;vi.spyOn(Math,'random').mockImplementation(()=>values[index++%values.length])});
afterEach(() => { cleanup(); localStorage.clear(); vi.restoreAllMocks(); });
it('无 WebGL 时可完成咖啡任务并返回城市',async()=>{
  render(<App/>);fireEvent.click(screen.getByRole('button',{name:/开始体验/}));
  await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('当前设备无法显示'));
  fireEvent.click(screen.getByRole('button',{name:'进入咖啡店'}));
  expect(screen.getByText('必须完成 5 个目标：')).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button',{name:'进入咖啡店'}));
  fireEvent.change(screen.getByRole('textbox'),{target:{value:'Cho tôi một ly cà phê sữa đá, ít đường, mang đi nhé.'}});
  fireEvent.click(screen.getByRole('button',{name:'发送'}));
  expect(screen.getByText('4/5')).toBeInTheDocument();
  await waitFor(()=>expect(screen.getByText('Bạn muốn thanh toán bằng cách nào?')).toBeInTheDocument());
  fireEvent.change(screen.getByRole('textbox'),{target:{value:'Tôi thanh toán.'}});
  fireEvent.click(screen.getByRole('button',{name:'发送'}));
  await waitFor(()=>expect(screen.getByText('任务报告 · 已保存到本机')).toBeInTheDocument());
  expect(JSON.parse(localStorage.getItem('hanoi-one-day-reports')!)[0].score).toBe(100);
  fireEvent.click(screen.getByRole('button',{name:'返回城市地图'}));
  expect(screen.getByRole('heading',{name:'今天，从河内出发。'})).toBeInTheDocument();
});
