import { createPortal } from 'react-dom';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { STALLS,MARKET_KEY,readMarket,newMarket,balance,money,marketTurn,buyMarket,marketComplete,type StallId } from './market';
import { requestMarketReply } from './ai';
import './market.css';

export default function MarketScene(){
  const [save,setSave]=useState(readMarket),[active,setActive]=useState<StallId|null>(null),[travelling,setTravelling]=useState<StallId|null>(null),[ready,setReady]=useState(false),[fallback,setFallback]=useState(false),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[report,setReport]=useState(false),[notice,setNotice]=useState('');
  const host=useRef<HTMLDivElement>(null),pins=useRef(new Map<StallId,HTMLButtonElement>()),handle=useRef<ReturnType<typeof import('./marketRenderer')['mountMarket']>|null>(null),alive=useRef(true),travelLock=useRef(false),requestLock=useRef(false),log=useRef<HTMLDivElement>(null);
  useEffect(()=>{alive.current=true;let cancelled=false;import('./marketRenderer').then(({mountMarket})=>{if(cancelled||!host.current)return;try{handle.current=mountMarket(host.current,pins.current);setReady(true);}catch{setFallback(true);}}).catch(()=>{if(!cancelled)setFallback(true);});return()=>{cancelled=true;alive.current=false;handle.current?.dispose();handle.current=null;};},[]);
  useEffect(()=>{try{localStorage.setItem(MARKET_KEY,JSON.stringify(save));}catch{setNotice('本机存储空间不足，离开前请完成本轮采购。');}},[save]);
  useEffect(()=>{log.current?.scrollTo?.({top:log.current.scrollHeight,behavior:'smooth'});},[save,active,busy]);
  useEffect(()=>{if(!active&&!report)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const vp=window.visualViewport;const update=()=>{document.documentElement.style.setProperty('--market-height',`${vp?.height||window.innerHeight}px`);document.documentElement.style.setProperty('--market-top',`${vp?.offsetTop||0}px`);};update();vp?.addEventListener('resize',update);vp?.addEventListener('scroll',update);return()=>{document.body.style.overflow=old;vp?.removeEventListener('resize',update);vp?.removeEventListener('scroll',update);};},[active,report]);
  const visit=async(id:StallId)=>{if(travelLock.current||requestLock.current)return;travelLock.current=true;setTravelling(id);setNotice('');let ok=true;try{if(handle.current)ok=await handle.current.travelTo(id);}catch{ok=false;}if(!alive.current)return;travelLock.current=false;setTravelling(null);if(!ok){setNotice('这条路暂时走不通，请再选一次摊位。');return;}setSave(s=>({...s,visited:[...new Set([...s.visited,id])]}));setActive(id);setInput('');};
  const stall=STALLS.find(t=>t.id===active);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!active||!input.trim()||requestLock.current)return;requestLock.current=true;setBusy(true);setNotice('');const id=active,result=marketTurn(save,id,input.trim());setSave(result.state);setInput('');
    const ai=await requestMarketReply({stall:id,messages:result.state.history[id].slice(0,-1).slice(-6),price:result.state.quotes[id],event:result.event,suggestedReply:result.reply});
    if(!alive.current)return;if(ai)setSave(s=>({...s,history:{...s.history,[id]:[...s.history[id].slice(0,-1),{role:'clerk',...ai}]}}));else setNotice('当前使用基础对话，仍可问价、议价和购买。');setBusy(false);requestLock.current=false;
  };
  const buy=()=>{if(!active||busy)return;const next=buyMarket(save,active);if(next===save){setNotice(balance(save)<save.quotes[active]?'预算不够，先试试议价，或换个摊位。':'先和摊主交流，再确认购买。');return;}setSave(next);setNotice('已放入购物袋，价格和预算已更新。');};
  return <div className="market-shell"><header className="market-heading"><div><p>CHỢ ĐỒNG XUÂN / 10:30</p><h2>把河内，装进购物袋。</h2><span>自由逛摊 · 越南语议价 · 市场体验版</span></div><div className="market-wallet"><small>剩余预算</small><strong>{money(balance(save))}</strong></div></header>
    <div className="market-objective"><span>采购委托</span><b className={save.purchases.fruit!==undefined?'bought':''}>① 两公斤芒果</b><b className={save.purchases.gifts!==undefined?'bought':''}>② 一盒伴手礼</b><b className={save.bargains.some(id=>save.purchases[id]!==undefined)?'bought':''}>③ 议价后成交一次</b></div>
    <div className="market-world"><div ref={host} className="market-canvas" role="img" aria-label="同春市场独立立体沙盘，三个摊位由中央步行通道连接"/>
      <div className="market-map-title"><strong>ĐỒNG XUÂN</strong><span>市场内街 / 点击摊位出发</span></div>
      {STALLS.map(t=><button key={t.id} ref={el=>{if(el)pins.current.set(t.id,el);else pins.current.delete(t.id);}} hidden={!ready} className={`market-pin ${save.purchases[t.id]!==undefined?'is-bought':''}`} disabled={!!travelling} onClick={()=>void visit(t.id)} aria-label={`前往${t.name}`}><span>{t.icon}</span><strong>{t.name}<small>{t.vi} {save.purchases[t.id]!==undefined?'· 已购':'↗'}</small></strong></button>)}
      {!ready&&<div className="market-fallback">{fallback?'当前设备使用简易地图，采购功能仍可体验。':'正在摆好摊位…'}{fallback&&STALLS.map(t=><button key={t.id} onClick={()=>void visit(t.id)}>{t.icon} {t.name}</button>)}</div>}
      {travelling&&<div className="market-travelling" role="status">小旅人正在前往 {STALLS.find(t=>t.id===travelling)?.name}…</div>}
      <div className="market-map-note">入口 → 中央通道 → 摊位 · 北 N ↑</div>
    </div>
    <footer className="market-bag"><div><strong>🛍 购物袋 · {Object.keys(save.purchases).length} 件</strong><span>{Object.keys(save.purchases).length?STALLS.filter(t=>save.purchases[t.id]!==undefined).map(t=>t.item).join(' / '):'带着 200,000₫ 出发，先问问价格吧。'}</span></div><button onClick={()=>setReport(true)}>{marketComplete(save)?'完成采购，查看报告':'查看采购进度'}</button></footer>
    {stall&&active&&createPortal(<div className="market-overlay"><section className="market-dialog" role="dialog" aria-modal="true" aria-label={stall.name}><header><div><small>{stall.vi}</small><h3>{stall.icon} {stall.name}</h3><p>{stall.vendor} · {stall.personality}</p></div><button disabled={busy} onClick={()=>setActive(null)} aria-label="回到市场沙盘">✕</button></header><div className="market-quote"><span>{stall.item}</span><strong>{money(save.quotes[active])}<small>整份总价</small></strong></div><div className="market-messages" ref={log} aria-live="polite"><div className="market-message clerk"><small>{stall.vendor}</small>Chào bạn! Bạn muốn xem gì?<span>你好！想看看什么？</span></div>{save.history[active].slice(0,busy?-1:undefined).map((m,i)=><div className={`market-message ${m.role}`} key={i}><small>{m.role==='user'?'你':stall.vendor}</small>{m.vi}{m.zh&&<span>{m.zh}</span>}</div>)}{busy&&<div className="market-message clerk">摊主正在回应<span className="market-dots"> …</span></div>}</div><details className="market-help"><summary>随身短语本</summary><p>Bao nhiêu tiền?（多少钱？）<br/>Bớt một chút được không?（可以便宜一点吗？）<br/>Tôi lấy nhé.（我要了。）</p><small>试试自己输入理由和目标价，例如“Bớt còn 95 nghìn được không?”</small></details>{notice&&<p className="market-notice" role="status">{notice}</p>}<form onSubmit={submit} className="market-composer"><input aria-label="与摊主用越南语交流" placeholder="试着询价，或提出你的价格…" maxLength={320} value={input} onChange={e=>setInput(e.target.value)} disabled={busy}/><button disabled={busy||!input.trim()}>发送</button></form><button className="market-buy" onClick={buy} disabled={busy||save.purchases[active]!==undefined}>{save.purchases[active]!==undefined?'✓ 已购买':`确认购买 · ${money(save.quotes[active])}`}</button></section></div>,document.body)}
    {report&&createPortal(<div className="market-overlay"><section className="market-dialog market-report" role="dialog" aria-modal="true" aria-label="市场采购报告"><small>YOUR MARKET JOURNAL</small><h3>{marketComplete(save)?'采购完成，满载而归。':'采购进行中'}</h3><p>已探索 {save.visited.length}/3 个摊位 · 剩余 {money(balance(save))}</p>{STALLS.map(t=><div className="market-receipt" key={t.id}><span>{t.icon} {t.item}</span><strong>{save.purchases[t.id]!==undefined?money(save.purchases[t.id]!):'未购买'}</strong></div>)}<p>节省了 {money(STALLS.reduce((sum,t)=>sum+(save.purchases[t.id]!==undefined?t.price-save.purchases[t.id]!:0),0))}，成交议价 {save.bargains.filter(id=>save.purchases[id]!==undefined).length} 次。</p><h4>下次试着这样说</h4><p>{save.bargains.length?'在付款前复述数量和总价，确认自己理解无误。':'提出合理的价格，并加上礼貌请求。'}</p><blockquote>{save.bargains.length?'Tổng cộng bao nhiêu tiền?':'Bớt cho tôi một chút được không?'}</blockquote><small>体验版报告基于采购记录；完整语言评分与随机事件将在后续扩展。</small><button className="market-buy" onClick={()=>setReport(false)}>继续逛市场</button>{marketComplete(save)&&<button onClick={()=>{setSave(newMarket());setReport(false);}}>开启新一轮采购</button>}</section></div>,document.body)}
    {!active&&!report&&<button className="market-restart" onClick={()=>{setSave(newMarket());setNotice('');}}>重新采购（清空本轮记录）</button>}
  </div>;
}
